# Extra autostart processes

# Set vscode workspace
windowrule = workspace 3, match:class ^(code)$
windowrule = match:workspace 3, group deny
windowrule = match:class ^code$, group override set always

# Set discord workspace
windowrule = workspace 4, match:class ^(discord)$

# Launch programs
exec-once = discord
exec-once = code
exec-once = ~/.config/hypr/autostart-inet.sh &
