# Scratch Pad
workspace = special:scratchpad , on-created-empty:exec spotify --class spotify & exec obsidian --class obsidian

# Spotify
windowrule = match:class spotify, float on
windowrule = match:class spotify, size 60% 50%
windowrule = match:class spotify, workspace special:scratchpad silent
windowrule = match:class spotify, size 844 919
windowrule = match:class spotify, move 22 92

# Obsidian
windowrule = match:class obsidian, float on
windowrule = match:class obsidian, size 60% 50%
windowrule = match:class obsidian, workspace special:scratchpad silent
windowrule = match:class obsidian, size 1024 919
windowrule = match:class obsidian, move 876 92

# sleep 3 && hyprctl activewindow | wl-copy
